server:
  port: 8082

token:
  saga:
    recovery:
      enabled: true
      stale-minutes: 10
      fixed-delay-ms: 60000

spring:
  application:
    name: token-service
  config:
    import: "optional:configserver:http://localhost:8888"
  flyway:
    enabled: true
    locations: classpath:db/migration
