spring:
  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:8081


gateway:
  api-key:
    enabled: true
    auth-server-url: http://auth-server:8081

logging:
  level:
    com.netflix.discovery: ERROR
    org.springframework.cloud.netflix.eureka: ERROR
